---
title           : "The impact of public investment on open-source digital infrastructure ecosystems hosted on GitHub"
subtitle        : "Pre-analysis Plan"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Paul Sharratt
    affiliation : 

affiliation:
    institution : The Hertie School


output: prereg::prereg_pdf
---

# Pre-Analysis Plan

## Summary
<!-- Provide the working title of your study. It may be the same title that you submit for publication of your final manuscript, but it is not a requirement. The title should be a specific and informative description of a project. Vague titles such as 'Fruit fly preregistration plan' are not appropriate.

Example: Effect of sugar on brownie tastiness. -->

This project investigates the impact of public investment on open-source software. My objective is to examine the impact of financial support, in the form of contracted software development payments funded by the Sovereign Tech Fund, impacts various key metrics within open-source digital infrastructure ecosystems hosted on GitHub.

**Data**

In order to answer this question, I am collecting or have collected data from two main sources; contractual data from the Sovereign Tech Fund and GitHub activity using GitHub’s REST API or a data collection and visualisation tool called Augur developed by the CHAOSS (Community Health Analytics in Open Source Software). In addition, I intend to utilize selected metrics for assessing opens-source ecosystem health developed by CHAOSS and, if possible, include measurements of open-source security from the [Open Source Security Foundation](https://securityscorecards.dev/). Currently, I have two methods for collecting data on GitHub organizations and repositories described below. In the course of the next weeks, I expect to settle on one data collection method. 

**Method**

This research employs a quantitative data analysis methodology, relying on publicly available data from GitHub and other relevant sources. The methodology comprises essential stages, including data collection, data cleaning, and preprocessing of GitHub repository data, public investment data, and supplementary repository security data.

To ascertain the relationships between public investment and the open-source health metrics, advanced statistical analyses, I intend to use a regression discontinuity design. This will be applied to investigate the impact of public investment on GitHub activity, community health metrics, and security within select open-source digital infrastructure projects.

**Importance**

This research holds considerable significance as it advances our understanding of the role of public investment in fostering open-source digital infrastructure projects. It directly aligns with the mission of the Sovereign Tech Fund and benefits from collaboration with researchers from the CHAOSS project at the Linux Foundation. The findings will offer valuable insights for policymakers and organizations like the Sovereign Tech Fund, demonstrating the potential benefits of strategic investments in open digital infrastructure. By addressing this question, I aim to inform evidence-based policy decisions and contribute to the responsible allocation of public resources in the digital age, with the support of key stakeholders in Germany and the open-source community.

**Support**

The project will be carried out in collaboration with the Sovereign Tech Fund, supported by SPRIND (the Bundesagentur für Sprunginnovationen) and the Federal Ministry for Economic Affairs and Climate Action of Germany, alongside support from researchers from the CHAOSS (Community Health Analytics in Open Source Software) project at the Linux Foundation.


## Motivation and Background
<!-- Please give a brief description of your study, including some background, the purpose of the of the study, or broad research questions. The description should be no longer than the length of an abstract. It can give some context for the proposed study, but great detail is not needed here for your preregistration.

Example: Though there is strong evidence to suggest that sugar affects taste preferences, the effect has never been demonstrated in brownies. Therefore, we will measure taste preference for four different levels of sugar concentration in a standard brownie recipe to determine if the effect exists in this pastry. -->

The research question of how public investment impacts open-source software ecosystems holds interest for me for several reasons. Firstly, as the digital transition accelerates, more aspects of our daily lives and essential services are becoming reliant on open-source software. Understanding and funding this infrastructure is vital for the sustainable development of society. Increasingly, state actors are engaging in the funding, development, and adoption of open-source software. In the European context, this initiative is taking place under the auspices of the broader digital sovereignty policy paradigm. The possible development of European Public Digital Infrastructure Fund illustrates the increasing attention paid to 

Secondly, my interest in this topic is rooted in my current part-time position with the Sovereign Tech Fund. This role has provided me with insights into the intricacies of public investment in technology projects, which is directly relevant to the subject of this research. My prior coursework has given me a solid foundation in statistical analysis, econometrics, and data management, all of which are crucial for conducting empirical research in this domain. After graduating from the Hertie, I hope to work for the Sovereign Tech Fund full-time and continue to work on addressing the research question and other related topics. 

Finally, through this research project, I hope to improve my data science skills. Despite never having taken Statistics II, I hope to become proficient in advanced statistical techniques, such as regression discontinuity design and time-series analysis. This research will also deepen my understanding of open-source software development and community dynamics, and improve my Python, R, and SQL skills.  Ultimately, this project will equip me with the skills to assess the effectiveness of public investments in technological innovation.


## Introduction
<!-- List specific, concise, and testable hypotheses. Please state if the hypotheses are directional or non-directional. If directional, state the direction. A predicted effect is also appropriate here. If a specific interaction or moderation is important to your research, you can list that as a separate hypothesis.

Example: If taste affects preference, then mean preference indices will be higher with higher concentrations of sugar. -->

The research question is situated within a broader context of digital infrastructure, digital policy, and the growing significance of open source software. Modern digital infrastructure is built with and relies on the development of open source software. For a general overview of the increasing importance of and lack of institutional support for public digital infrastructure, Nadia Eghbal’s report for the Ford Foundation, Roads and Bridges, is instructive.

There is a considerable amount of research constructing and presenting indicators of open source project activity, but a lack of consensus about how indicators derived from trace data might be used to represent a coherent view of open source project health and sustainability.

Currently, some 27 organizations that host their code on GitHub have received funding for work from the Sovereign Tech Fund. The duration, volume, and type of work varies from project to project. Between them, these 27 organizations account for 470 repositories on GitHub. These repositories range from simple [READ.ME](http://read.me/) repositories to large and complex repositories with multiple dependencies in a range of programming languages.

The key researcher here is Sean Goggins

### Key Papers

**Paper 1. - Open Source Community Health: Analytical Metrics and Their Corresponding Narratives**

The paper "Open Source Community Health: Analytical Metrics and Their Corresponding Narratives" by Sean Goggins et al. explores the evaluation of open source projects' health and sustainability. It emphasizes the limitations of existing methods that primarily rely on trace data and proposes an approach integrating field research and metric standards development. The paper presents the work of the Linux Foundation's CHAOSS project over four years, highlighting the importance of metrics that incorporate comparison, transparency, trajectory, and visualization. This approach aims to provide a comprehensive understanding of open source software health, connecting trace data with human experience. The relevance to your thesis lies in its focus on assessing open source ecosystem health, an aspect central to understanding the impact of public investment on such projects.

**Paper 2. - GitHub Sponsors**

The paper "GitHub Sponsors: Exploring a New Way to Contribute to Open Source" investigates the GitHub Sponsors program, examining characteristics of sponsored developers, sponsors, and the effects of sponsorship. It employs mixed methods, including data analysis and surveys, to understand the impact of financial support on open-source developers. The findings suggest that sponsored developers are more active, and the presence of sponsorship influences the community dynamics. This paper's focus on the economic aspects of open-source projects and the impact of financial support aligns closely with your thesis topic, especially in understanding how financial investments can influence open-source software ecosystems.

The quantitative methods used in the "GitHub Sponsors" paper include data analysis of the GitHub Sponsors program. This involves statistical analysis of the characteristics of sponsored developers, sponsors, and their activities on GitHub. The paper utilizes metrics related to the developers' activities and sponsorships, such as the number of sponsors, the frequency of contributions, and the nature of these contributions. This approach helps quantify the impact of financial sponsorship on developer engagement and community dynamics within open source projects.

Similarly, as Goggins et al. note, the demand for coherent, consistent and actionable metrics is growing as a result of state and corporate engagement with and investment in open source. I hope that through this research project, I can get to grips with these debates and, if possible, make a useful contribution.

### Ethical Considerations

Given that this project concerns open-source software, it is important to highlight the particular ethical components of research in this field. In this regard, Amanda Casari, Julia Ferraioli, and Juniper Lovato’s paper [Beyond the Repository](https://cacm.acm.org/magazines/2023/10/276630-beyond-the-repository/fulltext) will be a key reference point for this research project.


## Research Question
<!-- In this section, you will be asked to describe the overall design of your study. Remember that this research plan is designed to register a single study, so if you have multiple experimental designs, please complete a separate preregistration. -->

The central research question for this project is: 

**RQ1: What is the impact of public investment on open-source digital infrastructure ecosystems hosted on GitHub?**

In order to operationalize this research question, there are a number of hypotheses that I wish to test:

1.  that funding from the Sovereign Tech Fund leads to changes in activity on GitHub (such as commits, pushes, code additions & deletions) in specific repositories of software ecosystems  
2. that funding from the Sovereign Tech Fund leads to changes in measures of community health (such as the number and make-up of contributors on GitHub) of a given open-source software ecosystem
3. that funding from the Sovereign Tech Fund leads to changes in measures of software health (such as responsiveness to issues on GitHub) of a given open-source software ecosystem
4. that funding from the Sovereign Tech Fund leads to changes in measures of the security (such as the OSSF Security Score) of a given open-source software ecosystem hosted on GitHub

In the course of the thesis, I hope also to make inferences about the kind of metrics that would be useful for analyzing specifically the subset of open-source projects that are funded and supported by the Sovereign Tech Fund.

## Data and Methods
<!-- In this section, you will be asked to describe the overall design of your study. Remember that this research plan is designed to register a single study, so if you have multiple experimental designs, please complete a separate preregistration. -->


# Data Report

## Blinding
<!-- Blinding describes who is aware of the experimental manipulations within a study. Select all that apply. Is there any additional blinding in this study? -->

No blinding is involved in this study.

For studies that involve human subjects, they will not know the treatment group to which they have been assigned.

Personnel who interact directly with the study subjects (either human or non-human subjects) will not be aware of the assigned treatments.

Personnel who analyze the data collected from the study are not aware of the treatment applied to any given group.


## Method
<!-- Describe your study design. Examples include two-group, factorial, randomized block, and repeated measures. Is it a between (unpaired), within-subject (paired), or mixed design? Describe any counterbalancing required. Typical study designs for observation studies include cohort, cross sectional, and case-control studies.

This question has a variety of possible answers. The key is for a researcher to be as detailed as is necessary given the specifics of their design. Be careful to determine if every parameter has been specified in the description of the study design. There may be some overlap between this question and the following questions. That is OK, as long as sufficient detail is given in one of the areas to provide all of the requested information. For example, if the study design describes a complete factorial, 2 X 3 design and the treatments and levels are specified previously, you do not have to repeat that information.

Example: We have a between subjects design with 1 factor (sugar by mass) with 4 levels. -->

Enter your response here.


## Randomization
<!-- If you are doing a randomized study, how will you randomize, and at what level? Typical randomization techniques include: simple, block, stratified, and adaptive covariate randomization. If randomization is required for the study, the method should be specified here, not simply the source of random numbers.

Example: We will use block randomization, where each participant will be randomly assigned to one of the four equally sized, predetermined blocks. The random number list used to create these four blocks will be created using the web applications available at https://random.org. -->

Enter your response here.


# Sampling Plan
<!-- In this section we’ll ask you to describe how you plan to collect samples, as well as the number of samples you plan to collect and your rationale for this decision. Please keep in mind that the data described in this section should be the actual data used for analysis, so if you are using a subset of a larger dataset, please describe the subset that will actually be used in your study. -->






## Data collection procedures
<!-- Please describe the process by which you will collect your data. If you are using human subjects, this should include the population from which you obtain subjects, recruitment efforts, payment for participation, how subjects will be selected for eligibility from the initial pool (e.g. inclusion and exclusion rules), and your study timeline. For studies that donÍt include human subjects, include information about how you will collect samples, duration of data gathering efforts, source or location of samples, or batch numbers you will use.

The answer to this question requires a specific set of instructions so that another person could repeat the data collection procedures and recreate the study population. Alternatively, if the study population would be unable to be reproduced because it relies on a specific set of circumstances unlikely to be recreated (e.g., a community of people from a specific time and location), the criteria and methods for creating the group and the rationale for this unique set of subjects should be clear.

Example: Participants will be recruited through advertisements at local pastry shops. Participants will be paid $10 for agreeing to participate (raised to $30 if our sample size is not reached within 15 days of beginning recruitment). Participants must be at least 18 years old and be able to eat the ingredients of the pastries. -->

Enter your response here.


## Sample size
<!-- Describe the sample size of your study. How many units will be analyzed in the study? This could be the number of people, birds, classrooms, plots, interactions, or countries included. If the units are not individuals, then describe the size requirements for each unit. If you are using a clustered or multilevel design, how many units are you collecting at each level of the analysis? For some studies, this will simply be the number of samples or the number of clusters. For others, this could be an expected range, minimum, or maximum number.

Example: Our target sample size is 280 participants. We will attempt to recruit up to 320, assuming that not all will complete the total task. -->

Enter your response here.


## Sample size rationale
<!-- This could include a power analysis or an arbitrary constraint such as time, money, or personnel. This gives you an opportunity to specifically state how the sample size will be determined. A wide range of possible answers is acceptable; remember that transparency is more important than principled justifications. If you state any reason for a sample size upfront, it is better than stating no reason and leaving the reader to "fill in the blanks." Acceptable rationales include: a power analysis, an arbitrary number of subjects, or a number based on time or monetary constraints.

Example: We used the software program G*Power to conduct a power analysis. Our goal was to obtain .95 power to detect a medium effect size of .25 at the standard .05 alpha error probability. -->

Enter your response here.



# Variables
<!-- In this section you can describe all variables (both manipulated and measured variables) that will later be used in your confirmatory analysis plan. In your analysis plan, you will have the opportunity to describe how each variable will be used. If you have variables which you are measuring for exploratory analyses, you are not required to list them, though you are permitted to do so. -->


## Manipulated variables
<!-- Describe all variables you plan to manipulate and the levels or treatment arms of each variable. This is not applicable to any observational study. For any experimental manipulation, you should give a precise definition of each manipulated variable. This must include a precise description of the levels at which each variable will be set, or a specific definition for each categorical treatment. For example, “loud or quiet,” should instead give either a precise decibel level or a means of recreating each level. 'Presence/absence' or 'positive/negative' is an acceptable description if the variable is precisely described.

Example: We manipulated the percentage of sugar by mass added to brownies. The four levels of this categorical variable are: 15%, 20%, 25%, or 40% cane sugar by mass. -->

Enter your response here.


## Measured variables
<!-- Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study.

Observational studies and meta-analyses will include only measured variables. As with the previous questions, the answers here must be precise. For example, 'intelligence,' 'accuracy,' 'aggression,' and 'color' are too vague. Acceptable alternatives could be 'IQ as measured by Wechsler Adult Intelligence Scale' 'percent correct,' 'number of threat displays,' and 'percent reflectance at 400 nm.'

Example: The single outcome variable will be the perceived tastiness of the single brownie each participant will eat. We will measure this by asking participants ‘How much did you enjoy eating the brownie’ (on a scale of 1-7, 1 being 'not at all', 7 being 'a great deal') and 'How good did the brownie taste' (on a scale of 1-7, 1 being 'very bad', 7 being 'very good'). -->

Enter your response here.



# Analysis Plan
<!-- You may describe one or more confirmatory analysis in this preregistration. Please remember that all analyses specified below must be reported in the final article, and any additional analyses must be noted as exploratory or hypothesis generating.

A confirmatory analysis plan must state up front which variables are predictors (independent) and which are the outcomes (dependent), otherwise it is an exploratory analysis. You are allowed to describe any exploratory work here, but a clear confirmatory analysis is required. -->


# References
## 
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
\noindent
